### ISSUE TITLE
Call dropped after ~10-12 seconds

### ISSUE THREAD

**Issue by kirtan403** [mattermost/mattermost-plugin-calls#220]
I've a setup running in the docker. Just installed the v9.0.0 from the marketplace. 

I can see it has the port mapping of 8065 - tcp port.

Now, from the calls plugins settings page, I see there is some UDP port to mention. I kept it default, but it is not working.

What else should I need to do? This docker setup is running in a raspberry pi with cloudflare tunnel (which also acts as a reverse proxy) and the tunnel url is given in the DNS records.

Any port mapping I need to do in docker or any DNS entries?

Here are the call logs:
```
com.mattermost.calls: a/v device change detected
com.mattermost.calls_20b1f0b7d4b3b754_bundle.js:2 com.mattermost.calls: a/v device change detected
com.mattermost.calls_20b1f0b7d4b3b754_bundle.js:2 [Deprecation] The ScriptProcessorNode is deprecated. Use AudioWorkletNode instead. (https://bit.ly/audio-worklet)
ki @ com.mattermost.calls_20b1f0b7d4b3b754_bundle.js:2
initVAD @ com.mattermost.calls_20b1f0b7d4b3b754_bundle.js:2
initAudio @ com.mattermost.calls_20b1f0b7d4b3b754_bundle.js:2
await in initAudio (async)
init @ com.mattermost.calls_20b1f0b7d4b3b754_bundle.js:2
await in init (async)
s @ com.mattermost.calls_20b1f0b7d4b3b754_bundle.js:2
a @ com.mattermost.calls_20b1f0b7d4b3b754_bundle.js:2
(anonymous) @ com.mattermost.calls_20b1f0b7d4b3b754_bundle.js:2
s @ call_button.tsx:56
s @ react-dom.production.min.js:14
c @ react-dom.production.min.js:14
(anonymous) @ react-dom.production.min.js:14
F @ react-dom.production.min.js:15
ot @ react-dom.production.min.js:52
at @ react-dom.production.min.js:51
rt @ react-dom.production.min.js:52
mt @ react-dom.production.min.js:56
x @ react-dom.production.min.js:287
G @ react-dom.production.min.js:19
Jt @ react-dom.production.min.js:70
Zt @ react-dom.production.min.js:69
t.unstable_runWithPriority @ scheduler.production.min.js:19
Yi @ react-dom.production.min.js:122
v @ react-dom.production.min.js:287
Vt @ react-dom.production.min.js:68
c @ rocket-loader.min.js:1
com.mattermost.calls_20b1f0b7d4b3b754_bundle.js:2 com.mattermost.calls: vad: noise avg 24 58.67592592592592
com.mattermost.calls_20b1f0b7d4b3b754_bundle.js:2 com.mattermost.calls: ws: new conn id from server
com.mattermost.calls_20b1f0b7d4b3b754_bundle.js:2 com.mattermost.calls: ws: setting original conn id
com.mattermost.calls_20b1f0b7d4b3b754_bundle.js:2 com.mattermost.calls: ws open, sending join msg
com.mattermost.calls_20b1f0b7d4b3b754_bundle.js:2 com.mattermost.calls: join ack received, initializing connection
com.mattermost.calls_20b1f0b7d4b3b754_bundle.js:2 com.mattermost.calls: local signal: {"type":"offer","sdp":"v=0\r\no=- 2631070512264055518 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0\r\na=extmap-allow-mixed\r\na=msid-semantic: WMS\r\nm=application 9 UDP/DTLS/SCTP webrtc-datachannel\r\nc=IN IP4 0.0.0.0\r\na=ice-ufrag:Vpnt\r\na=ice-pwd:b5tMsPoVLpo5xO+EG4a02kxY\r\na=ice-options:trickle\r\na=fingerprint:sha-256 BB:2B:01:66:E1:86:48:B7:16:9C:47:47:6E:0B:14:1A:12:72:EB:99:7F:7E:B4:58:94:E0:64:D7:54:F9:39:42\r\na=setup:actpass\r\na=mid:0\r\na=sctp-port:5000\r\na=max-message-size:262144\r\n"}
com.mattermost.calls_20b1f0b7d4b3b754_bundle.js:2 com.mattermost.calls: remote signal {"type":"answer","sdp":"v=0\r\no=- 1259815370657842333 1665117303 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\na=fingerprint:sha-256 3F:C5:B2:A4:1D:38:D1:F4:C3:42:64:87:31:E0:52:AD:24:B4:B3:03:C0:B7:C0:88:62:D9:E2:99:52:95:9B:94\r\na=extmap-allow-mixed\r\na=group:BUNDLE 0\r\nm=application 9 UDP/DTLS/SCTP webrtc-datachannel\r\nc=IN IP4 0.0.0.0\r\na=setup:active\r\na=mid:0\r\na=sendrecv\r\na=sctp-port:5000\r\na=ice-ufrag:djMsRFIPlupdYEFJ\r\na=ice-pwd:mFHPeOkIJiseguSprAlhBODdGBiMPzWG\r\n"}
com.mattermost.calls_20b1f0b7d4b3b754_bundle.js:2 com.mattermost.calls: remote signal {"candidate":{"candidate":"candidate:3460764426 1 udp 2130706431 122.170.105.202 8443 typ host","sdpMid":"","sdpMLineIndex":0,"usernameFragment":null},"type":"candidate"}
com.mattermost.calls_20b1f0b7d4b3b754_bundle.js:2 com.mattermost.calls: remote signal {"candidate":{"candidate":"candidate:1990777822 1 udp 1694498815 122.170.105.202 33739 typ srflx raddr 0.0.0.0 rport 33739","sdpMid":"","sdpMLineIndex":0,"usernameFragment":null},"type":"candidate"}
com.mattermost.calls_20b1f0b7d4b3b754_bundle.js:2 com.mattermost.calls: rtc closed
com.mattermost.calls_20b1f0b7d4b3b754_bundle.js:2 com.mattermost.calls: disconnect
com.mattermost.calls_20b1f0b7d4b3b754_bundle.js:2 com.mattermost.calls: websocket reconnect handler
com.mattermost.calls_20b1f0b7d4b3b754_bundle.js:2 com.mattermost.calls: resetting state
```

**Comment by supergeoff** [comment]
Hello. Same issue here with a docker-compose without nginx setup. The call start, the information about transmission seams to be ok (caller light up when they talk) but no sound and connection drops automatically after a few seconds.

**Comment by supergeoff** [comment]
Solved by exposing 8443 on container then exposing the container over UDP on same port via DNS and setting the hostname in ICE Host Override.

**Comment by kirtan403** [comment]
@supergeoff can you please share your docker compose changes?

**Comment by streamer45** [comment]
Indeed, the connection dropping after a few seconds is a timeout meaning connectivity cannot be established. The solution is to open the configured RTC port (default is 8443) in the incoming direction, UDP protocol and set the `ICE Host Override` if needed to be the client facing IP address of the Mattermost instance.

@kirtan403 Please have a look at https://github.com/mattermost/mattermost-plugin-calls/issues/131#issuecomment-1271321055

**Comment by streamer45** [comment]
That won't work easily then. Ideally there should be a direct connection path from clients (users) to the Mattermost instance through port 8443. A proxy in between can only work if it supports forwarding UDP. But even then you'd need to at least know the IP address (or hostname) of such proxy and set it as the `ICE Host Override`.

**Comment by kirtan403** [comment]
I have mattermost installed at `chat.mycompany.com` that is configured to listen on `localhost:8065`

For calls, as you said, I created another CNAME record at `calls-chat.mycompany.com` that is configured to listen on `localhost:8443`. 

Added the `ICE Host Override` to `calls-chat.mycompany.com` and `RTC Server Port` to `8443`. Still it is not working. 

I think I'm still missing something...

**Comment by streamer45** [comment]
What does `calls-chat.mycompany.com` point to? If it's cloudflare then it won't work unless they support forwarding UDP (I doubt it but worth checking). The hostname should point directly to your Mattermost instance which should have a public IP most likely.

**Comment by kirtan403** [comment]
It is hosted on the raspberry pi. So doesn't have any public IP present. I need to check with the cloudflare if it does support port mapping as well for the tunnel, but I doubt it will.

**Comment by supergeoff** [comment]
> @supergeoff can you please share your docker compose changes?

I would not be able to share my docker compose since I host Mattermost in the Cloud (AWS) on a Fargate instance (it more like a CDK template). But I mostly implemented @streamer45 ideas. I have a public Application Loadbalancer (for HTTP trafic) routing trafic on port 443 to the app on the Fargate instance on port 8065 and exposed using a CNAME record (mattermost.my-domain.com). And a Network Loadbalancer (for UDP trafic) routing trafic to the app on the Fargate instance on port 8443 and exposed using another CNAME record (mattermostvoice.my-domain.com).

**Comment by streamer45** [comment]
Closing this for now as it likely relates to network configuration. Please feel free to reopen if you need more help on this.

**Comment by p3k** [comment]
i just had the same issue and was able to resolve it by changing the nat settings on my router from _symmetric_ to _cone_:

![image](https://user-images.githubusercontent.com/16631/203809723-348e9572-a7ed-405d-8319-04a8e7a50411.png)

maybe this helps someone else, too.
